In [1]:
import pandas as pd
import numpy as np

In [2]:
quora_quest = pd.read_csv('C:\\Users\\ebineet\\Documents\\GitHub\\NLP\\UPDATED_NLP_COURSE\\05-Topic-Modeling\\quora_questions.csv')

In [3]:
quora_quest

Question
0       What is the step by step guide to invest in sh...
1       What is the story of Kohinoor (Koh-i-Noor) Dia...
2       How can I increase the speed of my internet co...
3       Why am I mentally very lonely? How can I solve...
4       Which one dissolve in water quikly sugar, salt...
...                                                   ...
404284  How many keywords are there in the Racket prog...
404285          Do you believe there is life after death?
404286                                  What is one coin?
404287  What is the approx annual cost of living while...
404288              What is like to have sex with cousin?

[404289 rows x 1 columns]

In [4]:
quora_quest.head()

Question
0  What is the step by step guide to invest in sh...
1  What is the story of Kohinoor (Koh-i-Noor) Dia...
2  How can I increase the speed of my internet co...
3  Why am I mentally very lonely? How can I solve...
4  Which one dissolve in water quikly sugar, salt...

In [5]:
quora_quest['Question'][0]

'What is the step by step guide to invest in share market in india?'

In [6]:
len(quora_quest)

404289

In [7]:
#Pre-processing data

from sklearn.feature_extraction.text import CountVectorizer

In [8]:
# CV will have 3 parameters
# 1. # max_df gets rid of the VERY(MAX) common words. 0.9= discard word that show up in 90% of doc
# 2. # min_df gets rid of the LEAST common word. (minimum doc. freq)
# 3. Stop_words
cv= CountVectorizer(max_df=0.9,min_df=2,stop_words='english' )

In [9]:
dtm= cv.fit_transform(quora_quest['Question'])

In [10]:
dtm

<404289x38669 sparse matrix of type '<class 'numpy.int64'>'
	with 2002912 stored elements in Compressed Sparse Row format>

In [11]:
print(dtm)

  (0, 32971)	2
  (0, 15464)	1
  (0, 18192)	1
  (0, 31209)	1
  (0, 21408)	1
  (0, 17507)	1
  (1, 33107)	1
  (1, 19517)	1
  (1, 19516)	1
  (1, 23974)	1
  (1, 10406)	1
  (2, 17461)	1
  (2, 32487)	1
  (2, 18048)	1
  (2, 8270)	1
  (2, 36497)	1
  (2, 37248)	1
  (3, 21937)	1
  (3, 20643)	1
  (3, 32229)	1
  (4, 10826)	1
  (4, 37475)	1
  (4, 28022)	1
  (4, 33474)	1
  (4, 30230)	1
  :	:
  (404283, 30453)	1
  (404283, 16508)	1
  (404283, 18548)	1
  (404284, 27370)	1
  (404284, 19824)	1
  (404284, 19889)	1
  (404284, 19259)	1
  (404284, 36862)	1
  (404284, 28105)	1
  (404285, 20286)	1
  (404285, 9691)	1
  (404285, 4525)	1
  (404286, 7700)	1
  (404287, 33248)	1
  (404287, 8722)	1
  (404287, 17511)	1
  (404287, 20499)	1
  (404287, 33257)	1
  (404287, 7043)	1
  (404287, 2776)	1
  (404287, 3045)	1
  (404287, 35890)	1
  (404288, 20333)	1
  (404288, 31115)	1
  (404288, 8818)	1


# <span class="mark">LDA</span>

In [12]:
from sklearn.decomposition import LatentDirichletAllocation

In [13]:
lda= LatentDirichletAllocation(n_components=20, random_state=42)

In [14]:
lda.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=20, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

# Grab the vocab of Words

In [15]:
# instance of all the words.
len(cv.get_feature_names())

38669

In [16]:
type(cv.get_feature_names())

list

In [17]:
# to get the word at location 500000
cv.get_feature_names()[1000]

'560'

In [18]:
import random
random_word_id = random.randint(0,54777)
cv.get_feature_names()[random_word_id]

'vulnerabilities'

# Grab the topics

In [19]:
# Check the length of Components(Topic)
len(lda.components_)

20

In [20]:
type(lda.components_)

numpy.ndarray

In [21]:
lda.components_.shape

(20, 38669)

In [22]:
lda.components_

array([[0.05      , 0.05      , 0.05      , ..., 0.05      , 2.05      ,
        0.05      ],
       [0.05      , 0.17695522, 0.05      , ..., 0.05      , 0.05      ,
        0.05      ],
       [0.05      , 0.05      , 0.05      , ..., 0.05      , 0.05      ,
        0.05      ],
       ...,
       [0.05      , 0.05      , 0.05      , ..., 0.05      , 0.05      ,
        0.05      ],
       [0.69097673, 0.05      , 0.05      , ..., 0.05      , 0.05      ,
        0.05      ],
       [0.05      , 0.05      , 0.05      , ..., 2.05      , 0.05      ,
        2.05      ]])

In [23]:
single_topic = lda.components_[0]

In [24]:
single_topic.argsort()

array([19334, 20888, 20886, ..., 16359, 31059,  4632], dtype=int64)

In [25]:
import numpy as np
arr = np.array([10,200,1])
arr

array([ 10, 200,   1])

In [26]:
# WILL GIVE THE INDEX OF THE VALUE STORED IN ASCENDING ORDER.
# SHOWS THE LOCATION  OF LARGER VARIABLES.
arr.argsort()

array([2, 0, 1], dtype=int64)

# GET THE HIGH PROBABLITY WORDS

In [27]:
# LAST 10 VALUES of arsort()
# garb the last 10 values

single_topic.argsort()[-10:]

array([21780, 15073, 15060,  7968, 17507, 32134,  6350, 16359, 31059,
        4632], dtype=int64)

In [28]:
top_twenty_words=single_topic.argsort()[-20:]

In [29]:
for index in top_twenty_words:
    print(cv.get_feature_names()[index])

heard
ve
source
options
companies
sydney
development
code
open
services
media
google
good
company
india
social
career
history
service
best


# Grab the highest probability of words

In [30]:
#lda= LatentDirichletAllocation(n_components=7, random_state=42)# only 6 topocs got printed because lad = 

for i,topic in enumerate(lda.components_):
    print(f"The TOP 15 Words for TOPIC # {i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')

The TOP 15 Words for TOPIC # 0
['sydney', 'development', 'code', 'open', 'services', 'media', 'google', 'good', 'company', 'india', 'social', 'career', 'history', 'service', 'best']




The TOP 15 Words for TOPIC # 1
['economy', 'process', 'making', 'government', 'rupee', 'india', 'word', 'money', 'rs', 'english', 'black', 'indian', '1000', 'notes', '500']




The TOP 15 Words for TOPIC # 2
['current', 'ones', 'alcohol', 'center', 'legal', 'home', 'state', 'compare', 'man', 'purpose', 'good', 'india', 'cost', 'average', 'does']




The TOP 15 Words for TOPIC # 3
['answers', 'year', 'facts', 'apple', 'mind', 'series', 'looking', 'interesting', 'worth', 'big', 'exist', 'tv', 'does', 'iphone', 'new']




The TOP 15 Words for TOPIC # 4
['australia', 'overcome', 'usa', 'students', 'student', 'visa', 'canada', 'mba', 'apply', 'jobs', 'college', 'differences', 'india', 'car', 'job']




The TOP 15 Words for TOPIC # 5
['different', 'russia', 'win', 'relationship', 'culture', 'countries', 'paki

In [31]:
dtm

<404289x38669 sparse matrix of type '<class 'numpy.int64'>'
	with 2002912 stored elements in Compressed Sparse Row format>

In [32]:
quora_quest

Question
0       What is the step by step guide to invest in sh...
1       What is the story of Kohinoor (Koh-i-Noor) Dia...
2       How can I increase the speed of my internet co...
3       Why am I mentally very lonely? How can I solve...
4       Which one dissolve in water quikly sugar, salt...
...                                                   ...
404284  How many keywords are there in the Racket prog...
404285          Do you believe there is life after death?
404286                                  What is one coin?
404287  What is the approx annual cost of living while...
404288              What is like to have sex with cousin?

[404289 rows x 1 columns]

In [33]:
topic_results= lda.transform(dtm)

In [34]:
topic_results.shape

(404289, 20)

In [35]:
topic_results[0]

array([0.00625   , 0.00625   , 0.00625   , 0.00625   , 0.00625   ,
       0.00625   , 0.00625   , 0.17117952, 0.00625   , 0.30852663,
       0.00625   , 0.00625   , 0.00625   , 0.00625   , 0.00625   ,
       0.00625   , 0.41404385, 0.00625   , 0.00625   , 0.00625   ])

In [36]:
# argmax()---->Returns the index position of highest probabilty
topic_results[0].argmax()

16

In [37]:
quora_quest['Topic']= topic_results.argmax(axis=1)

In [38]:
quora_quest.head()

Question  Topic
0  What is the step by step guide to invest in sh...     16
1  What is the story of Kohinoor (Koh-i-Noor) Dia...     17
2  How can I increase the speed of my internet co...      8
3  Why am I mentally very lonely? How can I solve...     19
4  Which one dissolve in water quikly sugar, salt...     17