In [18]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ebineet\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ebineet\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ebineet\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


True

In [11]:
paragraph = """I have three visions for India.In 3000 years of our history, people from all over the world have come and invaded us, 
captured our lands, conquered our minds. From Alexander onwards, the Greeks, the Turks, the Moguls, 
the Portuguese, the British, the French, the Dutch, all of them came and looted us, took over what was ours. 
Yet, we have not done this to any other nation. We have not conquered anyone. We have not grabbed their land, 
their culture, their history and tried to enforce our way of life on them. Why? Because we respect the freedom of others.
That is why my first vision is that of freedom.I believe that India got its first vision of this in 1857, when we started the war 
of Independence. It is this freedom that we must protect and nurture and build on. If we are not free, no one will respect us.
My second vision for India’s development.For fifty years we have been a developing nation. It is time we see ourselves as a developed nation. 
We are among top five nations of the world in terms of GDP. We have 10 per cent growth rate in most areas. Our poverty levels are falling. 
Our achievements are being globally recognised today. Yet we lack the self-confidence to see ourselves as a developed nation, self-reliant and self-assured. 
Isn’t this incorrect?I have a third vision.India must stand up to the world. Because I believe that, unless India stands up to the world, 
no one will respect us. Only strength respects strength. We must be strong not only as a military power but also as an economic power. 
Both must go hand-in-hand.My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Department of Space, Professor Satish Dhawan, 
who succeeded him and Dr.Brahm Prakash, the father of nuclear material. I was lucky to have worked with all three of them closely and consider this the great 
opportunity of my life."""

# Text pre processing or cleaning the text.

1. Lowering the text.
2. Stemming and lemmatization.
3. remoal of stop words.
4. removal of punctuation.

<span class="mark">PorterStemmer</span> is used for stemming and <span class="girk">WordNetlemmatizer</span> is used of lemmatization.

In [14]:
# Cleaning of text

import re   # import Regular Expression
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer  # for stemming
from nltk.stem import WordNetLemmatizer   # for lemmatization

ps = PorterStemmer() # object created
wordnet = WordNetLemmatizer() # object created
sentences =  nltk.sent_tokenize(paragraph)  # converting the para to sentences
corpus=[]
for i in range(len(sentences)):
    review= re.sub('[^a-zA-z]', ' ', sentences[i]) # cleaning the sentences with punctuations.
    review= review.lower()  # converting to lower case
    review= review.split()  # split to get list of words
    review= [ps.stem(word) for word in review if not word in set(stopwords.words('english'))] # stemming
    review=' '.join(review)
    corpus.append(review)

In [13]:
# Breaking of para to sentences.
sentences

['I have three visions for India.In 3000 years of our history, people from all over the world have come and invaded us, \ncaptured our lands, conquered our minds.',
 'From Alexander onwards, the Greeks, the Turks, the Moguls, \nthe Portuguese, the British, the French, the Dutch, all of them came and looted us, took over what was ours.',
 'Yet, we have not done this to any other nation.',
 'We have not conquered anyone.',
 'We have not grabbed their land, \ntheir culture, their history and tried to enforce our way of life on them.',
 'Why?',
 'Because we respect the freedom of others.',
 'That is why my first vision is that of freedom.I believe that India got its first vision of this in 1857, when we started the war \nof Independence.',
 'It is this freedom that we must protect and nurture and build on.',
 'If we are not free, no one will respect us.',
 'My second vision for India’s development.For fifty years we have been a developing nation.',
 'It is time we see ourselves as a develo

In [16]:
# the corpus after all the cleaning is done.
corpus

['three vision india year histori peopl world come invad us captur land conquer mind',
 'alexand onward greek turk mogul portugues british french dutch came loot us took',
 'yet done nation',
 'conquer anyon',
 'grab land cultur histori tri enforc way life',
 '',
 'respect freedom other',
 'first vision freedom believ india got first vision start war independ',
 'freedom must protect nurtur build',
 'free one respect us',
 'second vision india develop fifti year develop nation',
 'time see develop nation',
 'among top five nation world term gdp',
 'per cent growth rate area',
 'poverti level fall',
 'achiev global recognis today',
 'yet lack self confid see develop nation self reliant self assur',
 'incorrect third vision india must stand world',
 'believ unless india stand world one respect us',
 'strength respect strength',
 'must strong militari power also econom power',
 'must go hand hand good fortun work three great mind',
 'dr vikram sarabhai depart space professor satish dhawan

# For Lemmatization....

After lemmatization the corpus will change to a more meaningful sentence than that after stemming.
Check teh corpus after stemming and lemmatization.

In [22]:
# Cleaning of text

import re   # import Regular Expression
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer  # for stemming
from nltk.stem import WordNetLemmatizer   # for lemmatization

ps = PorterStemmer() # object created
wordnet = WordNetLemmatizer() # object created
sentences =  nltk.sent_tokenize(paragraph)  # converting the para to sentences
corpus=[]
for i in range(len(sentences)):
    review= re.sub('[^a-zA-z]', ' ', sentences[i]) # cleaning the sentences with punctuations.
    review= review.lower()  # converting to lower case
    review= review.split()  # split to get list of words
    review= [wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))] # stemming
    review=' '.join(review)
    corpus.append(review)

In [23]:
# the corpus after all the cleaning is done.
corpus

['three vision india year history people world come invaded u captured land conquered mind',
 'alexander onwards greek turk mogul portuguese british french dutch came looted u took',
 'yet done nation',
 'conquered anyone',
 'grabbed land culture history tried enforce way life',
 '',
 'respect freedom others',
 'first vision freedom believe india got first vision started war independence',
 'freedom must protect nurture build',
 'free one respect u',
 'second vision india development fifty year developing nation',
 'time see developed nation',
 'among top five nation world term gdp',
 'per cent growth rate area',
 'poverty level falling',
 'achievement globally recognised today',
 'yet lack self confidence see developed nation self reliant self assured',
 'incorrect third vision india must stand world',
 'believe unless india stand world one respect u',
 'strength respect strength',
 'must strong military power also economic power',
 'must go hand hand good fortune worked three great m

In [26]:
# Creating the BOW Model: Document Matrix
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x= cv.fit_transform(corpus).toarray() # covert to array to see properly

In [28]:
print(x)

[[0 0 0 ... 1 1 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# Print entire Sparse Matrix with truncation(...)

In [30]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

In [31]:
print(x)

[[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
  0 0 1 1 0]
 [0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
  0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0
  0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0
  0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 