# Assign a Topic To Each Of the Article given in npr dataset.

In [1]:
import pandas as pd

In [2]:
npr = pd.read_csv('C:\\Users\\ebineet\\Documents\\GitHub\\NLP\\UPDATED_NLP_COURSE\\05-Topic-Modeling\\npr.csv')

In [3]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [4]:
npr['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [5]:
len(npr)

11992

In [7]:
#Pre-processing data

from sklearn.feature_extraction.text import CountVectorizer

In [8]:
# CV will have 3 parameters
# 1. # max_df gets rid of the VERY(MAX) common words. 0.9= discard word that show up in 90% of doc
# 2. # min_df gets rid of the LEAST common word. (minimum doc. freq)
# 3. Stop_words
cv= CountVectorizer(max_df=0.9,min_df=2,stop_words='english' )

Document Term Matrix (dtm).

<span class="burk">No SPLITTTING required as there is no Label It is unsupervised Learning,</span>

Fit_transform will be applied to the entire daatset.

In [9]:
dtm= cv.fit_transform(npr['Article'])

In [10]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [11]:
print(dtm)

  (0, 53112)	2
  (0, 436)	3
  (0, 37382)	2
  (0, 5867)	1
  (0, 37411)	2
  (0, 43740)	1
  (0, 54403)	3
  (0, 44460)	2
  (0, 28875)	3
  (0, 44648)	1
  (0, 16578)	1
  (0, 12950)	1
  (0, 604)	1
  (0, 38079)	6
  (0, 34145)	15
  (0, 32459)	1
  (0, 42732)	1
  (0, 42390)	9
  (0, 2437)	2
  (0, 25508)	5
  (0, 16123)	4
  (0, 26752)	3
  (0, 10646)	1
  (0, 41011)	4
  (0, 29070)	1
  :	:
  (11991, 4315)	1
  (11991, 28887)	1
  (11991, 32585)	1
  (11991, 50599)	1
  (11991, 9067)	1
  (11991, 38652)	1
  (11991, 47768)	2
  (11991, 33536)	1
  (11991, 16527)	1
  (11991, 41081)	1
  (11991, 14611)	1
  (11991, 28356)	1
  (11991, 35785)	1
  (11991, 33620)	14
  (11991, 7316)	1
  (11991, 45088)	1
  (11991, 22720)	1
  (11991, 51838)	1
  (11991, 37235)	1
  (11991, 49654)	1
  (11991, 15275)	1
  (11991, 53567)	1
  (11991, 12752)	1
  (11991, 20202)	1
  (11991, 47633)	11


# <span class="mark">LDA</span>

In [12]:
from sklearn.decomposition import LatentDirichletAllocation

In [13]:
lda= LatentDirichletAllocation(n_components=7, random_state=42)

In [14]:
lda.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=7, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

# Grab the vocab of Words

In [15]:
# instance of all the words.
len(cv.get_feature_names())

54777

In [16]:
type(cv.get_feature_names())

list

In [17]:
# to get the word at location 500000
cv.get_feature_names()[41000]

'reproductive'

In [20]:
import random
random_word_id = random.randint(0,54777)
cv.get_feature_names()[random_word_id]

'sharp'

# Grab the topics

In [21]:
# Check the length of Components (TOPIC)
len(lda.components_)

7

In [22]:
type(lda.components_)

numpy.ndarray

In [23]:
lda.components_.shape

(7, 54777)

In [24]:
lda.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [25]:
single_topic = lda.components_[0]

In [26]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [28]:
import numpy as np

In [29]:
arr = np.array([10,200,1])

In [30]:
arr

array([ 10, 200,   1])

In [31]:
# WILL GIVE THE INDEX OF THE VALUE STORED IN ASCENDING ORDER.
# SHOWS THE LOCATION  OF LARGER VARIABLES.
arr.argsort()

array([2, 0, 1], dtype=int64)

# GET THE HIGH PROBABLITY WORDS

In [33]:
# LAST 10 VALUES of arsort()
# garb the last 10 values

single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [34]:
top_ten_words=single_topic.argsort()[-10:]

In [36]:
for index in top_ten_words:
    print(cv.get_feature_names()[index])

new
percent
government
company
million
care
people
health
said
says


In [37]:
top_twenty_words=single_topic.argsort()[-20:]

In [38]:
for index in top_twenty_words:
    print(cv.get_feature_names()[index])

president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


# Grab the highest probability of words

In [40]:
#lda= LatentDirichletAllocation(n_components=7, random_state=42)# only 6 topocs got printed because lad = 

for i,topic in enumerate(lda.components_):
    print(f"The TOP 15 Words for TOPIC # {i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')

The TOP 15 Words for TOPIC # 0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']




The TOP 15 Words for TOPIC # 1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']




The TOP 15 Words for TOPIC # 2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']




The TOP 15 Words for TOPIC # 3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']




The TOP 15 Words for TOPIC # 4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']




The TOP 15 Words for TOPIC # 5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 

In [41]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [42]:
npr

Article
0      In the Washington of 2016, even when the polic...
1        Donald Trump has used Twitter  —   his prefe...
2        Donald Trump is unabashedly praising Russian...
3      Updated at 2:50 p. m. ET, Russian President Vl...
4      From photography, illustration and video, to d...
...                                                  ...
11987  The number of law enforcement officers shot an...
11988    Trump is busy these days with victory tours,...
11989  It’s always interesting for the Goats and Soda...
11990  The election of Donald Trump was a surprise to...
11991  Voters in the English city of Sunderland did s...

[11992 rows x 1 columns]

In [44]:
topic_results= lda.transform(dtm)

In [45]:
topic_results.shape

(11992, 7)

In [47]:
topic_results[0]

array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
       2.99652737e-01, 2.25479379e-04, 2.25497980e-04])

In [49]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [50]:
# argmax()---->Returns the index position of highest probabilty
topic_results[0].argmax()

1

In [51]:
npr['Topic']= topic_results.argmax(axis=1)

In [52]:
npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      0

[11992 rows x 2 columns]